apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  # Base64 encoded values
  # your_super_secret_jwt_key_for_k8s -> eW91cl9zdXBlcl9zZWNyZXRfand0X2tleV9mb3Jfazhz
  jwt-secret: eW91cl9zdXBlcl9zZWNyZXRfand0X2tleV9mb3Jfazhz
